<<<<<<< HEAD
print ("luka adamshvili")
print ("luka khakhidze")
print ("luka kochlamazashvili")
print ("nikoloz chagelishvili")
print ("nikoloz oqropiridze")
print ("nikoloz khaplanishvili")
print ("aleqsandere xasaia")
print ("gabrile kilasonia")
print ("andria xubulovi")
print ("tinano toriashvili")
print ("anastasia jeiranashvili")
print ("ana giorgadze")
print ("babrale khaplanishvili")
print ("marta gabrielashvili")
print ("solome gelovani")
print ("gega revazishvili")
print ("anastasia paniashvili")
print ("akaki shoshitashvili")
print ("demetre levanidze")
print ("lilu talakhdze")
print ("tamari baratashvili")
=======
print ("luka adamshvili")
print ("luka khakhidze")
print ("luka kochlamazashvili")
print ("nikoloz chagelishvili")
print ("nikoloz oqropiridze")
print ("nikoloz khaplanishvili")
print ("aleqsandere xasaia")
print ("gabrile kilasonia")
print ("andria xubulovi")
print ("tinano toriashvili")
print ("anastasia jeiranashvili")
print ("ana giorgadze")
print ("babrale khaplanishvili")
print ("marta gabrielashvili")
print ("solome gelovani")
print ("gega revazishvili")
print ("anastasia paniashvili")
print ("akaki shoshitashvili")
print ("demetre levanidze")
print ("lilu talakhdze")
print ("tamari baratashvili")
print
>>>>>>> f001cf630c8ed146519bfc32411034f2eab25df3
